#!/usr/bin/env bash

dot=.
dir=`pwd`

# make a dir for the old backups
mkdir -p ../dotfiles.bak

for file in "`find . -name ".*" -type f`"
do
    mv ../$file ../dotfiles.bak/$file
    ln -s $dir/$file ~/$file
done
