#!/usr/bin/env bash

dot=.
dir=`pwd`

# make a dir for the old backups
mkdir -p ../dotfiles.bak

while read file; do
    mv ../$file ../dotfiles.bak/$file
    ln -s $dir/$file ~/$file
done < "$1.list"

