(defun resize-frame-height ()
  (interactive)
  (setq screen-height (x-display-pixel-height))
  (setq desired-frame-height (- screen-height 150))
  (setq frame-height-in-chars (/ desired-frame-height (frame-char-height)))
  (set-frame-height (selected-frame) frame-height-in-chars)
  )

(defun organize-frames-by-count (frame-count)
  (interactive)
  (set-frame-width (selected-frame) 80)
  (setq screen-width (x-display-pixel-width))
  (setq frame-width (frame-pixel-width (selected-frame)))
  (setq divisions (+ frame-count 1))
  (setq total-frame-width (* frame-width frame-count))
  (setq extra-space (- screen-width total-frame-width))
  (setq spacer (/ extra-space divisions))
  (setq w-top 60)
  (dotimes (i frame-count)
    (set-frame-width (selected-frame) 80)
    (setq frame-number (+ i 1))
    (setq w-left (+ (* spacer frame-number) (* frame-width i)))
    (set-frame-position (selected-frame) w-left w-top)
    (resize-frame-height)
    (if (> frame-count 1) (ns-next-frame))
    )
  )

(defun organize-frames-by-count2 (frame-count)
  (interactive)
  ;; set up your variables
  (set-frame-width (selected-frame) 80)
  (setq pad 10)
  (setq screen-width (x-display-pixel-width))
  (setq frame-width (frame-pixel-width (selected-frame)))
  (setq total-frame-width (* frame-width frame-count))
  (setq so2 (/ screen-width 2))
  (setq fo2 (/ total-frame-width 2))
  (setq po2 (/ pad 2))
  (setq start-pos (- (- so2 fo2) pad))
  (dotimes (i frame-count)
    (set-frame-width (selected-frame) 80)
    (setq new-pos (+ start-pos (* frame-width i)))
    (set-frame-position (selected-frame) (+ new-pos (* pad i)) 60)
    (resize-frame-height)
    (if (> frame-count 1) (ns-next-frame))
    (setq frame-number (+ i 1))
    )
  )

(defun organize-frames ()
  (interactive)
  (organize-frames-by-count2 (length (frame-list)))
  )

(defun center-frame ()
  (interactive)
  (organize-frames-by-count (+ 1 0))
  )

(provide 'cg-orgframes)
