set nocompatible
filetype off
call vundle#begin()
Bundle 'scrooloose/syntastic'
Bundle 'kien/ctrlp.vim'
Bundle 'rking/ag.vim'
Bundle 'ludovicchabant/vim-lawrencium'
Bundle 'SirVer/ultisnips'
Bundle 'terryma/vim-multiple-cursors'
Bundle 'tpope/vim-commentary'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-unimpaired'
Bundle 'vim-scripts/DirDiff.vim'
Bundle 'altercation/vim-colors-solarized'
Bundle 'bronson/vim-trailing-whitespace'
Bundle 'vim-scripts/occur.vim'
call vundle#end()
filetype on

syntax on "syntax highlighting
set nowmnu
set wildmode=full
" set hlsearch " highlight search
set autoindent "indent to the previous level
filetype plugin on "make commands smarter for your file ]m and the like
set clipboard=unnamed " set clipboard to system clipboard (gui compile req)
set backspace=2 " make backspace behave correctly!
set incsearch "jump to first match when searching
set tags=tags;/ "search for a tags file recursively till it finds one
set cc=72,79 "put a line for comments and end of code pep8
set expandtab shiftwidth=4 softtabstop=4
set tabstop=4
autocmd BufWritePre * :%s/\s\+$//e "delete trailing whitespace on save
set number " show line numbers
" set relativenumber " show the relative numbers
set autoread " automatically read files when changed by another editor
set hidden " just hide the buffer till I come back to it
set ignorecase " ignore case while searching
set wildignore+=*/.git/*,*/.hg/*,*.pyc,*.DS_Store "don't pick up certain things
set nofoldenable " no code folding ever!!!
set path=$PWD/**
set noswapfile
set nobackup
set complete=.,w,b,u,t "removed 'i' which scans all files in path
set completeopt=
set t_Co=256
set background=light
set laststatus=2 "always show status line
set iskeyword+=\-

" Solarized
colors solarized
let g:solarized_italic=0
let g:solarized_termcolors = 16
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
"
" Set extra options when running in GUI mode
if has("gui_running")
    set guioptions-=T
    set guioptions+=e
    set t_Co=256
    set guifont=Monaco:h11
    set guicursor=a:blinkon0
    colors solarized
    let g:solarized_italic=0
endif

" status line
set statusline=\                                    " start it off
set statusline+=%f\                                "File+path
set statusline+=%y\                                   "FileType
set statusline+=[%{&ff}]\                              "FileFormat (dos/unix..)
set statusline+=%m%r%w\                      "Modified? Readonly? Top/bot.
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
set statusline +=%=%5l             "current line
set statusline +=/%L\ \                "total lines

" syntastic
let g:syntastic_mode_map = { 'mode': 'passive' }
let g:syntastic_python_checkers = ['pyflakes']
let g:syntastic_javascript_checkers = ['jshint']

" CtrlP setup
let g:ctrlp_follow_symlinks = 1 "follow symlinks into the darkness
let g:ctrlp_extensions = ['tag'] "enable searching of tags
let g:ctrlp_working_path_mode = 0
let g:ctrlp_use_caching = 0

" dirdiff setup
let g:DirDiffExcludes = ".hg,tags,*.pyc,.*.swp,.DS_Store"
set diffopt+=context:99999
let g:DirDiffEnableMappings = 1

" custom functions...
function! NumberToggle()
    if (&relativenumber == 1)
        set norelativenumber
        set number
    elseif(&number == 1)
        set norelativenumber
        set nonumber
    else
        set number
        set relativenumber
    endif
endfunc

autocmd FileType python call Py_config()
    function Py_config()
        " call TextEnableCodeSnip('sql', "sql='''", "'''", 'Identifier')
        " call TextEnableCodeSnip('javascript', "js='''", "'''", 'Identifier')
    endfunction

" hard mode
" noremap <Up> <Nop>
" noremap <Down> <Nop>
" noremap <Left> <Nop>
" noremap <Right> <Nop>

" " save time on indenting things
" vnoremap < <gv
" vnoremap > >gv


" " custom keymaps for great things
nmap <leader>xe :%!openssl base64<cr>
nmap <leader>xd :%!openssl base64 -d<cr>
nmap <leader>j :set textwidth=70<cr>:r !date<cr><s-o><esc><s-o><cr>
nmap <leader>e :find<space>
nmap <leader>b :CtrlPBufTag<cr>
nmap <leader>v <c-w>v:vertical resize 90<cr><c-w>w:find<space>
nmap <leader>n :call NumberToggle()<cr>
nmap <leader>t :echo system("date +'%r'")<cr>
nmap <leader>dc 2<c-w>w]c
imap <NUL> <Space>
map <leader>] :split <CR>:exec("tag ".expand("<cword>"))<CR>
nmap <leader>p :w !python<cr>
