set nocompatible
filetype off
call vundle#begin()
" Bundle 'wting/rust.vim'
" Bundle 'justinmk/vim-sneak'
" Bundle 'Lokaltog/vim-easymotion'
Bundle 'scrooloose/syntastic'
" Bundle 'altercation/vim-colors-solarized'
" Bundle 'bkad/CamelCaseMotion'
" Bundle 'itchyny/lightline.vim'
" Bundle 'bling/vim-airline'
Bundle 'kien/ctrlp.vim'
Bundle 'rking/ag.vim'
Bundle 'ludovicchabant/vim-lawrencium'
" Bundle 'davidhalter/jedi-vim'
" Bundle 'mileszs/ack.vim'
Bundle 'SirVer/ultisnips'
Bundle 'terryma/vim-multiple-cursors'
Bundle 'tpope/vim-commentary'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-unimpaired'
Bundle 'vim-scripts/DirDiff.vim'
" Bundle 'chriskempson/tomorrow-theme'
call vundle#end()
filetype on

syntax on "syntax highlighting
filetype plugin on "make commands smarter for your file ]m and the like
set clipboard=unnamed " set clipboard to system clipboard (gui compile req)
set backspace=2 " make backspace behave correctly!
set incsearch "jump to first match when searching
set autoindent "indent to the previous level
set tags=tags;/ "search for a tags file recursively till it finds one
set cc=72,79 "put a line for comments and end of code pep8
set expandtab shiftwidth=4 softtabstop=4
set tabstop=4
autocmd BufWritePre * :%s/\s\+$//e "delete trailing whitespace on save
set number " show line numbers
set relativenumber " show the relative numbers
set autoread " automatically read files when changed by another editor
set hidden " just hide the buffer till I come back to it
set ignorecase " ignore case while searching
set wildignore+=*/.git/*,*/.hg/*,*.pyc,*.DS_Store "don't pick up certain things
set nofoldenable " no code folding ever!!!
set path=*/**
set noswapfile
set nobackup
set complete=.,w,b,u,t "removed 'i' which scans all files in path
set completeopt=
set t_Co=256
set laststatus=2 "always show status line
set iskeyword+=\-

" Set extra options when running in GUI mode
if has("gui_running")
    set guioptions-=T
    set guioptions+=e
    set t_Co=256
    set guifont=Monaco:h11
    set guicursor=a:blinkon0
    colors solarized
    let g:solarized_italic=0
endif

" hi StatusLine ctermbg=8 ctermfg=15

" default the statusline to green when entering Vim
" hi statusline guibg=green
" " lightline
let g:lightline = {}
let g:lightline.colorscheme = 'Tomorrow'
" let g:lightline.separator = { 'left': '>', 'right': '<' }

" solarized
" colors solarized
" let g:solarized_italic=0

"jedi
"

" status line
set statusline=\                                    " start it off
set statusline+=%f\                                "File+path
set statusline+=%y\                                   "FileType
set statusline+=[%{&ff}]\                              "FileFormat (dos/unix..)
set statusline+=%m%r%w\                      "Modified? Readonly? Top/bot.
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
set statusline +=%=%5l             "current line
set statusline +=/%L\ \                "total lines
hi statusline guibg=DarkGrey ctermfg=4 ctermbg=15
if version >= 700
  au InsertEnter * hi StatusLine ctermbg=15 ctermfg=1
  au InsertLeave * hi StatusLine ctermbg=15 ctermfg=4
endif

" syntastic
let g:syntastic_mode_map = { 'mode': 'passive' }
let g:syntastic_python_checkers = ['pyflakes']
let g:syntastic_javascript_checkers = ['jshint']

" CtrlP setup
let g:ctrlp_follow_symlinks = 1 "follow symlinks into the darkness
let g:ctrlp_extensions = ['tag'] "enable searching of tags
let g:ctrlp_working_path_mode = 0
let g:ctrlp_use_caching = 0

" dirdiff setup
let g:DirDiffExcludes = ".hg,tags,*.pyc,.*.swp,.DS_Store"
set diffopt+=context:99999
let g:DirDiffEnableMappings = 1

" custom functions...
function! NumberToggle()
    if (&relativenumber == 1)
        set norelativenumber
        set number
    elseif(&number == 1)
        set norelativenumber
        set nonumber
    else
        set number
        set relativenumber
    endif
endfunc

" syntax highlight sql strings in python
function! TextEnableCodeSnip(filetype,start,end,textSnipHl) abort
  let ft=toupper(a:filetype)
  let group='textGroup'.ft
  if exists('b:current_syntax')
    let s:current_syntax=b:current_syntax
    " Remove current syntax definition, as some syntax files (e.g. cpp.vim)
    " do nothing if b:current_syntax is defined.
    unlet b:current_syntax
  endif
  execute 'syntax include @'.group.' syntax/'.a:filetype.'.vim'
  try
    execute 'syntax include @'.group.' after/syntax/'.a:filetype.'.vim'
  catch
  endtry
  if exists('s:current_syntax')
    let b:current_syntax=s:current_syntax
  else
    unlet b:current_syntax
  endif
  execute 'syntax region textSnip'.ft.'
  \ matchgroup='.a:textSnipHl.'
  \ start="'.a:start.'" end="'.a:end.'"
  \ contains=@'.group
endfunction

autocmd FileType python call Py_config()
    function Py_config()
        " call TextEnableCodeSnip('sql', "sql='''", "'''", 'Identifier')
        " call TextEnableCodeSnip('javascript', "js='''", "'''", 'Identifier')
    endfunction

" hard mode
" noremap <Up> <Nop>
" noremap <Down> <Nop>
" noremap <Left> <Nop>
" noremap <Right> <Nop>

" " custom keymaps for great things
nmap <leader>xe :%!openssl base64<cr>
nmap <leader>xd :%!openssl base64 -d<cr>
nmap <leader>j :set textwidth=70<cr>:r !date<cr><s-o><esc><s-o><cr>
nmap <leader>e :find<space>
nmap <leader>b :CtrlPBufTag<cr>
nmap <leader>v <c-w>v:vertical resize 90<cr><c-w>w:find<space>
nmap <leader>n :call NumberToggle()<cr>
nmap <leader>t :echo system("date +'%r'")<cr>
nmap <leader>dc 2<c-w>w]c
" imap <c-n> <c-p>
imap <NUL> <Space>
map <leader>] :split <CR>:exec("tag ".expand("<cword>"))<CR>
nmap <leader>p :w !python<cr>
