set nocompatible
filetype off
set rtp+=~/.vim/Vundle.vim
call vundle#begin()
Bundle 'altercation/vim-colors-solarized'
Bundle 'bkad/CamelCaseMotion'
Bundle 'itchyny/lightline.vim'
Bundle 'kien/ctrlp.vim'
Bundle 'ludovicchabant/vim-lawrencium'
Bundle 'mileszs/ack.vim'
" Bundle 'scrooloose/syntastic'
Bundle 'SirVer/ultisnips'
Bundle 'terryma/vim-multiple-cursors'
Bundle 'tpope/vim-commentary'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-unimpaired'
Bundle 'vim-scripts/DirDiff.vim'
call vundle#end()
filetype on

syntax on "syntax highlighting
filetype plugin on "make commands smarter for your file ]m and the like
set clipboard=unnamed " set clipboard to system clipboard (gui compile req)
set backspace=2 " make backspace behave correctly!
set incsearch "jump to first match when searching
set autoindent "indent to the previous level
set tags=tags;/ "search for a tags file recursively till it finds one
set cc=72,79 "put a line for comments and end of code pep8
set expandtab shiftwidth=4 softtabstop=4
set tabstop=4
autocmd BufWritePre * :%s/\s\+$//e "delete trailing whitespace on save
set number " show line numbers
set relativenumber " show the relative numbers
set autoread " automatically read files when changed by another editor
set hidden " just hide the buffer till I come back to it
set ignorecase " ignore case while searching
set wildignore+=*/.git/*,*/.hg/*,*.pyc,*.DS_Store "don't pick up certain things
set nofoldenable " no code folding ever!!!
set path=*/**
set noswapfile
set nobackup
set complete=.,w,b,u,t "removed 'i' which scans all files in path
set completeopt=
set t_Co=256
set laststatus=2 "always show status line

" lightline
let g:lightline = {}
let g:lightline.colorscheme = 'solarized'
let g:lightline.separator = { 'left': '>', 'right': '<' }

" solarized
colors solarized
let g:solarized_italic=0

" syntastic
let g:syntastic_mode_map = { 'mode': 'passive' }
let g:syntastic_python_checkers = ['pyflakes']

" CtrlP setup
let g:ctrlp_follow_symlinks = 1 "follow symlinks into the darkness
let g:ctrlp_extensions = ['tag'] "enable searching of tags
let g:ctrlp_working_path_mode = 0

" dirdiff setup
let g:DirDiffExcludes = ".hg,tags,*.pyc,.*.swp,.DS_Store"
set diffopt+=context:99999

" custom functions...
function! NumberToggle()
    if (&relativenumber == 1)
        set norelativenumber
        set number
    elseif(&number == 1)
        set norelativenumber
        set nonumber
    else
        set number
        set relativenumber
    endif
endfunc

" " custom keymaps for great things
nmap <leader>e :CtrlP<cr>
nmap <leader>b :CtrlPBufTag<cr>
nmap <leader>v <c-w>v:vertical resize 90<cr><c-w>w
nmap <leader>n :call NumberToggle()<cr>
imap <NUL> <Space>
