" windows gVim config

" colors
" colorscheme github
" set bg=light
" colorscheme papercolor
hi Visual guibg=LightGoldenrod1 guifg=NONE

set guicursor+=a:blinkon0
" solarized
" set bg=light
" colorscheme solarized8_flat

" one
" set bg=light
" colorscheme one

" hi Visual  guifg=NONE guibg=#eeda86 gui=none

" fix diff colors
" DiffAdd
" DiffChange
" DiffDelete
" DiffText

" font test oO0 LliI {} () -_= ,.;:
" set guifont=Roboto_Mono_for_Powerline:h9
" set guifont=Anonymice_Powerline:h11
" set guifont=Source_Code_Pro_for_Powerline:h11
" set guifont=Inconsolata_for_Powerline:h11
" set guifont=Monofur_for_Powerline:h11
" set guifont=Space_Mono_for_Powerline:h9
" set guifont=Space_Mono_for_Powerline:h9
" set guifont=Cascadia_Code:h9
set guifont=SF_Mono:h10:W500:cANSI:qDRAFT

set go-=m  "remove menu bar
set go-=T  "remove toolbar
set go-=r  "remove right-hand scroll bar
set go-=L  "remove left-hand scroll bar

" no beeps!
set vb t_vb=
