set nocompatible
filetype off

if empty(glob('c:/Users/cguilbeau/.vim/autoload/plug.vim'))
         silent !curl -fLo c:/Users/cguilbeau/.vim/autoload/plug.vim --create-dirs
     \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('c:/Users/cguilbeau/.vim/plugged')

" Plug 'edvb/catium.vim'
Plug 'bronson/vim-trailing-whitespace'
Plug 'easymotion/vim-easymotion'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/vim-easy-align'
Plug 'ludovicchabant/vim-lawrencium'
Plug 'majutsushi/tagbar'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'vim-scripts/DirDiff.vim'
Plug 'vim-syntastic/syntastic'
call plug#end()

let g:python_highlight_all = 1
let g:airline#extensions#tagbar#flags = 'f'
let g:airline#extensions#branch#enabled = 0
let g:airline#extensions#tagbar#enabled = 0
let g:syntastic_always_populate_loc_list = 1

if $TERM_PROGRAM == 'iTerm.app'
    set bg=light
    colorscheme solarized
    let g:solarized_italic = 1
    hi DiffAdd      guifg=NONE
    hi DiffChange   gui=none guifg=NONE guibg=NONE
    hi DiffText     gui=bold guifg=NONE
endif

" no beeps!
autocmd! GUIEnter * set vb t_vb=

" diff
if has("patch-8.1.0360")
    set diffopt+=internal,algorithm:patience
endif
set diffopt+=internal,algorithm:patience

syntax on "syntax highlighting
set nowmnu
set wildmode=longest:full,full
filetype plugin on "make commands smarter for your file ]m and the like
filetype indent off
set autoindent "indent to the previous level
set clipboard=unnamed " set clipboard to system clipboard (gui compile req)
set backspace=2 " make backspace behave correctly!
set incsearch "jump to first match when searching
set tags=./tags,tags "look for a tags file all the way up till the root
set cc=80 " put a line at column 80
set expandtab shiftwidth=4 softtabstop=4 " use spaces for tabs and 4 wide
set tabstop=4 " tabstop every 4 spaces
autocmd BufWritePre * :%s/\s\+$//e "delete trailing whitespace on save
set autoread " automatically read files when changed by another editor
set hidden " just hide the buffer till I come back to it
set ignorecase " ignore case while searching
set wildignore+=*/.git/*,*/.hg/*,*.pyc,*.DS_Store "don't pick up certain things
set noswapfile
" set nobackup
set complete=.,w,b,u ",t,i
set completeopt=
set iskeyword+=\-
set shellslash " use forward slashes in paths like /ZogoTech/src
highlight CursorLine term=NONE ctermfg=NONE ctermbg=8 guibg=Grey40
highlight CursorColumn term=NONE ctermfg=NONE ctermbg=8 guibg=Grey40
set formatoptions +=j
set encoding=utf-8
set splitbelow
set showtabline=2

set foldmethod=indent
set foldlevelstart=20

" Set extra options when running in GUI mode
if has("gui_running")
    set go-=m  "remove menu bar
    set go-=T  "remove toolbar
    set go-=r  "remove right-hand scroll bar
    set go-=L  "remove left-hand scroll bar
    set t_Co=256
    set guicursor+=a:blinkon0
    set bg=light
    au CursorMoved * set guitablabel=%{tagbar#currenttag('%s','','f')}
    colorscheme default
    " set bg=light
    " colorscheme solarized
    let g:solarized_italic = 1
    hi DiffAdd      guifg=NONE
    hi DiffChange   gui=none guifg=NONE guibg=NONE
    hi DiffText     gui=bold guifg=NONE
endif

" grep
autocmd QuickFixCmdPost *grep* cwindow
if executable("rg")
    set grepprg=rg\ --vimgrep\ --follow
endif

" statusline
" set laststatus=2                                "always show status line
" set statusline=\                                " start it off
" set statusline+=%{fnamemodify(getcwd(),':t')}\  " this is so things will werk
" set statusline+=%{mode()}\                       "current mode
" set statusline+=%f\                             "File+path
" set statusline+=%t\                             "File-path
" set statusline+=%m%r%w\                         "Modified? Readonly? Top/bot.
" set statusline+=%#warningmsg#
" set statusline+=%{g:Catium()}
" set statusline+=%Y\                             "FileType
" set statusline+=%{&ff}\                       "FileFormat (dos/unix..)
" set statusline+=%*%=
" set statusline +=%5l                          "current line
" set statusline +=/%L                         "total lines
" set statusline +=:%c\                          "current char

" status line color change
" hi StatusLine term=None ctermfg=14 ctermbg=15
" hi StatusLineNC term=None cterm=underline ctermfg=14 ctermbg=7
" hi LineNr term=None ctermfg=14 ctermbg=7
" hi NonText term=None ctermfg=7 ctermbg=None
" hi SignColumn term=None ctermfg=None ctermbg=7
hi VertSplit term=None ctermfg=14 ctermbg=15 guibg='NONE' guifg=grey
set fillchars+=vert:\│
" set fillchars=vert:\▐
" set lsp=0

" python stuff
au BufNewFile,BufRead *.py
\ set cc=73,80

" NO MOUSE ALLOWED!
" set mouse=
:nmap <ScrollWheelUp> <nop>
:nmap <S-ScrollWheelUp> <nop>
:nmap <C-ScrollWheelUp> <nop>
:nmap <ScrollWheelDown> <nop>
:nmap <S-ScrollWheelDown> <nop>
:nmap <C-ScrollWheelDown> <nop>
:nmap <ScrollWheelLeft> <nop>
:nmap <S-ScrollWheelLeft> <nop>
:nmap <C-ScrollWheelLeft> <nop>
:nmap <ScrollWheelRight> <nop>
:nmap <S-ScrollWheelRight> <nop>
:nmap <C-ScrollWheelRight> <nop>

" FZF
let $FZF_DEFAULT_COMMAND = 'rg --files --follow --path-separator /'
" let $FZF_DEFAULT_OPTS = '--color=bw'
let $PYTHONUNBUFFERED = 1

" syntastic
let g:syntastic_python_checkers = ['pyflakes']
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_check_on_open = 1
let g:syntastic_ignore_files = ['/server/lib/core/schema.py', '\m\c\.min\.js']

" dirdiff setup
" exclude things in DirDiff
let g:DirDiffExcludes = ".hg,tags,*.pyc,.*.swp,.DS_Store,python,nginx,hg,ranet,__pycache__"
" no code folding ever in DirDiff
set diffopt+=context:99999
" next/prev file in list
nmap <leader>dj :DirDiffNext<cr>
nmap <leader>dk :DirDiffPrev<cr>
" goto the next (or first) change in the edited file
nmap <leader>dc 2<c-w>w]czz

" :nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>
:noremap <leader>h :set hlsearch! hlsearch?<CR>

" abbreviations
ab pdb import pdb; pdb.set_trace()
ab bp breakpoint()
ab slp from time import sleep; sleep(2)

function! Zinit()
    cd c:/ZogoTech/src-proj
    term ++close c:/ZogoTech/zbin/ztag.cmd
    let $FZF_DEFAULT_COMMAND = 'rg --files --follow --type=py --type=js --type=txt --type=css --path-separator /'
    edit .
endfunc

function! Zimport()
    term ++close c:/ZogoTech/zbin/clipimport.bat
endfunc

" " custom keymaps for great things
" majic killer for regresion results
map <A-.> <C-]>
nmap <leader>07 :%s/<c-r>=substitute(substitute(substitute(substitute(substitute(substitute(substitute(@0, 'ALVIN', '.*', 'g'), '\\', '\\\\', 'g'), '\]', '\\]', 'g'), '\[', '\\[', 'g'), '[0-9]\+', '\[0-9\]\\+', 'g'), '\n','\\n','g'), '/', '\\/', 'g')<CR>//gc
" quick encrypt/decrypt a file
nmap <leader>xe :%!openssl base64<cr>
nmap <leader>xd :%!openssl base64 -d<cr>
nmap <leader>e :FZF<cr>
nmap <leader>b :BTags<cr>
" vsplit clone and set window to 80 chars
nmap <leader>v <c-w>v:vertical resize 83<cr><c-w>w
" toggle line numbers
nmap <leader>n :set number!<cr>
" do an hg vdiff on the current file in a new tab
nmap <leader>hg :tabnew %<cr>:Hgvdiff<cr><c-w><c-r>
" reload the currenlty open file (for reloading vimrc)
nmap <leader>ii :so %<cr>
nmap <leader>zz :call Zinit()<cr>
imap <NUL> <Space>
nmap <leader>zi :call Zimport()<cr>
nmap <leader>pi P\si\si
nmap <leader>f zM
nmap <leader>ff zR
map <leader>si (/import<cr>V)k:sort i<cr>(/import<cr>V)k:EasyAlign<cr><c-x>import<cr>
vmap <leader>wc <esc>:set textwidth=79<cr>gvgq<esc>:set textwidth=0<cr>gv
vmap <leader>wt <esc>:set textwidth=72<cr>gvgq<esc>:set textwidth=0<cr>gv
nmap <leader>zc :tabnew<cr>:DirDiff c:/ZogoTech/src-hg c:/ZogoTech/src-proj<cr>
nmap <leader>zg :grep -tpy -w<Space>
nmap <leader>gg yiw:grep -m 120 -tpy -tjs -w """<cr>
nmap <leader>wsd :term<cr><C-W>N:on<cr>awsd -Sidls -m1<cr>
" disable things that accidentally get hit...
nmap <F1> <nop>
imap <F1> <nop>
vmap <S-Up> <nop>
vmap <S-Down> <nop>
nmap <S-Up> <nop>
nmap <S-Down> <nop>
nmap <leader>i :edit ~/.vim/vimrc<cr>
nmap <leader>r yiw:,$s/"//gc<left><left><left>
vmap <leader>r y:,$s/"//gc<left><left><left>
nmap <leader>hw yiw/"<cr>:set hlsearch<cr>
nmap s <Plug>(easymotion-s)
nmap <leader>jj :%!python -m json.tool<cr>
" terminal mappings
tnoremap <leader>f print('*' * 72)<cr>pp locals()<CR><C-W>N:on<cr>?c.*src.*.py.*[0-9]\+<cr>/[0-9]\+<cr>yiw?c.*src<cr><C-W>f:"<cr>zz:set cul<cr>:set number<cr><C-W><C-W>a<C-W><C-W>
tnoremap <leader>d d<cr>print('*' * 72)<cr>pp locals()<cr><C-W>N:sleep 100m<cr>a<C-W>N:on<cr>?c.*src.*.py.*[0-9]\+<cr>/[0-9]\+<cr>yiw?c.*src<cr><C-W>f:"<cr>zz: set cul<cr>:set number<cr><C-W><C-W>a
tnoremap <leader>u u<cr>print('*' * 72)<cr>pp locals()<cr><C-W>N:sleep 100m<cr>a<C-W>N:on<cr>?c.*src.*.py.*[0-9]\+<cr>/[0-9]\+<cr>yiw?c.*src<cr><C-W>f:"<cr>zz: set cul<cr>:set number<cr><C-W><C-W>a
tnoremap <leader>n n<cr>print('*' * 72)<cr>pp locals()<cr><C-W>N:sleep 100m<cr>a<C-W>N:on<cr>?c.*src.*.py.*[0-9]\+<cr>/[0-9]\+<cr>yiw?c.*src<cr><C-W>f:"<cr>zz: set cul<cr>:set number<cr><C-W><C-W>a
tnoremap <leader>s s<cr>print('*' * 72)<cr>pp locals()<cr><C-W>N:sleep 100m<cr>a<C-W>N:on<cr>?c.*src.*.py.*[0-9]\+<cr>/[0-9]\+<cr>yiw?c.*src<cr><C-W>f:"<cr>zz: set cul<cr>:set number<cr><C-W><C-W>a

" windows specific things
if has('win32')
    nmap <leader>i :edit ~/vimfiles/vimrc<cr>
    set guifont=Consolas:h11:cANSI:qDRAFT
    " set guifont=Courier_New:h10:cANSI:qDRAFT
    " set rop=type:directx
    " set guifont=CourierPrime:h10
    " set guifont=monofur:h10
    " set guifont=SF-Mono-Regular:h10
endif
if has('macunix')
    set guifont=Monaco:h13
endif

