set nocompatible
filetype off

let $VIMHOME=expand('~/dotfiles/')

" plugins
call plug#begin($VIMHOME.'/vim/plugged')
Plug 'dense-analysis/ale'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/vim-easy-align'
Plug 'justinmk/vim-sneak'
Plug 'ludovicchabant/vim-lawrencium'
Plug 'majutsushi/tagbar'
Plug 'maxbrunsfeld/vim-yankstack'
Plug 'mbbill/undotree'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vimjas/vim-python-pep8-indent'
call plug#end()

set bg=light

" ale
let g:ale_linters = { 'python': ['pyflakes'], 'javascript': ['jshint'] }
lef g:ale_jshint_config_loc = '$VIMHOME/dotfiles/jshint.config'
let g:python_pyflakes_executable = 'c:/ZogoTech/src/server/bin/zpyflakes'
let g:ale_enabled = 0
nmap <leader>ll :lopen<cr>
nmap <leader>lc :lclose<cr>

" sneak
let g:sneak#label = 1

" yankstack
call yankstack#setup()
nmap <leader>p <Plug>yankstack_substitute_older_paste
nmap <leader>P <Plug>yankstack_substitute_newer_paste

" lawrencium
nmap <leader>hg :tabnew %<cr>:Hgvdiff<cr><c-w><c-r>

" set spelling for hg commit messages
autocmd FileType hgcommit setlocal spell
autocmd FileType gitcommit setlocal spell

" vim settings
syntax on "syntax highlighting
set noto " wait forever for leader sequences
set showcmd " show command as you type it
set nowmnu
set wildmode=longest:full,full
filetype plugin on "make commands smarter for your file ]m and the like
filetype indent on
set clipboard=unnamed " set clipboard to system clipboard (gui compile req)
set backspace=2 " make backspace behave correctly!
set incsearch "jump to first match when searching
set tags=./tags,tags "look for a tags file all the way up till the root
set expandtab shiftwidth=4 softtabstop=4 " use spaces for tabs and 4 wide
set tabstop=4 " tabstop every 4 spaces
autocmd BufWritePre * :%s/\s\+$//e "delete trailing whitespace on save
set autoread " automatically read files when changed by another editor
set hidden " just hide the buffer till I come back to it
set ignorecase " ignore case while searching
set wildignore+=*/.git/*,*/.hg/*,*.pyc,*.DS_Store "don't pick up certain things
set noswapfile
" set nobackup
set complete=.,w,b,u ",t,i
set completeopt=
set iskeyword+=\-
set shellslash " use forward slashes in paths like /ZogoTech/src
" set formatoptions +=j
set encoding=utf-8
set splitbelow
" set foldmethod=indent
" set foldlevelstart=20
set cc=80 " put a line at column 80
nmap <leader>i :edit $VIMHOME/vim/vimrc<cr>
nmap <leader>ig :edit $VIMHOME/vim/gvimrc<cr>
nmap <leader>ii :so %<cr>
nmap <leader>h :set hlsearch! hlsearch?<CR>
nmap <leader>n :set number!<cr>
nmap <leader>r yiw:,$s/"//gc<left><left><left>
vmap <leader>r y:,$s/"//gc<left><left><left>
nmap <leader>v <c-w>v:vertical resize 85<cr><c-w>w
" set fillchars+=vert:┊
set fillchars+=vert:\  " remove the vert fill char
" no folding ever
au BufRead * set nofen
" persist the undos
" set undodir=~/.vim/undodir
" set undofile
set termguicolors " use all colors in terminal mode
set formatoptions+=l " dont ever wrap lines
set formatoptions+=j " Delete comment character when joining commented lines

" grep
autocmd QuickFixCmdPost *grep* cwindow
if executable("rg")
    set grepprg=rg\ --vimgrep\ --follow
endif
nmap <leader>g :grep -w<Space>

" statusline
set laststatus=2                                "always show status line
set statusline=\                                " start it off
set statusline+=%f\                             "File+path
set statusline+=%m\ "
if match(&runtimepath, 'Tagbar') != -1
    set statusline+=%{tagbar#currenttag('%s','','f')}
else
    echo "Tagbar Not Installed"
endif
set statusline+=%*%=
set statusline+=%R%W%Y
set statusline+=,%{&ff}                       "FileFormat (dos/unix..)
set statusline +=%5l                          "current line
set statusline +=/%L                         "total lines
set statusline +=\                              "just a space

" whitespace
fun! TrimWhitespace()
    let l:save = winsaveview()
    keeppatterns %s/\s\+$//e
    call winrestview(l:save)
endfun
autocmd BufWritePre * :call TrimWhitespace() " autotrim whitespace on save

" python stuff
let g:python_pep8_indent_multiline_string = -2
let g:python_pep8_indent_hang_closing = 1
au BufNewFile,BufRead *.py set cc=73,80
au BufNewFile,BufRead *.py call ale#toggle#Enable()
ab pdb breakpoint() # TODO: remove this!!!
vmap <leader>wc <esc>:set textwidth=79<cr>gvgq<esc>:set textwidth=0<cr>gv
vmap <leader>wt <esc>:set textwidth=72<cr>gvgq<esc>:set textwidth=0<cr>gv

" NO MOUSE ALLOWED!
" set mouse=
:nmap <ScrollWheelUp> <nop>
:nmap <S-ScrollWheelUp> <nop>
:nmap <C-ScrollWheelUp> <nop>
:nmap <ScrollWheelDown> <nop>
:nmap <S-ScrollWheelDown> <nop>
:nmap <C-ScrollWheelDown> <nop>
:nmap <ScrollWheelLeft> <nop>
:nmap <S-ScrollWheelLeft> <nop>
:nmap <C-ScrollWheelLeft> <nop>
:nmap <ScrollWheelRight> <nop>
:nmap <S-ScrollWheelRight> <nop>
:nmap <C-ScrollWheelRight> <nop>

" FZF
let $FZF_DEFAULT_COMMAND = 'rg --files --follow --path-separator /'
let $FZF_DEFAULT_OPTS = '--color=bw'
" let $FZF_DEFAULT_OPTS = '
"             \ --color fg:242,bg:236,hl:65,fg+:15,bg+:239,hl+:108
"             \ --color info:108,prompt:109,spinner:108,pointer:168,marker:168
"             \'
let $PYTHONUNBUFFERED = 1
nmap <leader>e :FZF<cr>
nmap <leader>b :BTags<cr>
nmap <leader>t :Tags<cr>

" DirDiff

" ZogoTech Stuff
function! Zinit()
    " change the root directory
    cd c:/ZogoTech/src
    " tag project files
    term ++close ctags -R --exclude=.hg --exclude=*.min.js --exclude=3p --languages=Python,Javascript --python-kinds=cfmvl appserver server webserver
    let $FZF_DEFAULT_COMMAND = 'rg --files --follow --type=py --type=js --type=txt --type=css --path-separator / appserver server webserver'
    set undodir=c:\ZogoTech\src\undodir
    set undofile
endfunc

function! Zimport()
    term ++close clipimport.bat
endfunc

" custom dirdiff
" function! Zdiff()
"     execute 'tabnew'
"     term /ZogoTech/src/python/python.exe /ZogoTech/scripts/zc.py
"     execute 'setlocal cursorline'
" endfunc

" set diffopt=
" if has("patch-8.1.0360")
"     set diffopt+=internal,algorithm:histogram,indent-heuristic,iblank
"     " set diffopt+=internal,algorithm:minimal,indent-heuristic,iblank
" endif

" DirDiff
set diffopt+=context:9999
hi DiffAdd ctermfg=15 guifg=NONE ctermbg=10 guibg=darkseagreen1
hi DiffChange ctermfg=15 guifg=black ctermbg=11 guibg=lightcyan1
hi DiffText ctermfg=15 guifg=black ctermbg=1 guibg=cadetblue1
hi DiffDelete ctermfg=15 guifg=mistyrose ctermbg=12 guibg=mistyrose

function! ZdiffDone(...)
    execute 'setlocal cursorline'
    nmap <buffer> <return> :on<cr>0/Z<cr><C-w>f<C-w>r<C-w><C-w>/c:<cr>v/differ<cr>hhy<C-w><C-w>:setlocal number<cr>:vert diffsplit "<cr>:setlocal number<cr><C-w><C-r>
endfunc

function! Zdiff()
    execute 'tabnew'
    call term_start("/ZogoTech/src/python/python.exe /ZogoTech/scripts/zc.py", {'exit_cb':function('ZdiffDone')})
endfunc

function! ZdiffPrompt()
    let curline = getline('.')
    call inputsave()
    let left = input('left: ')
    let right = input('left: ' . left . '; ' . 'right: ')
    call inputrestore()
    execute 'tabnew'
    call term_start("/ZogoTech/src/python/python.exe /ZogoTech/scripts/zc.py " . left . ' ' . right, {'exit_cb':function('ZdiffDone')})
endfunc

nmap <leader>dj :bufdo diffoff<cr><C-w>jj<return>
nmap <leader>dk :bufdo diffoff<cr><C-w>jk<return>

nmap <leader>07 :%s/<c-r>=substitute(substitute(substitute(substitute(substitute(substitute(substitute(@0, 'ALVIN', '.*', 'g'), '\\', '\\\\', 'g'), '\]', '\\]', 'g'), '\[', '\\[', 'g'), '[0-9]\+', '\[0-9\]\\+', 'g'), '\n','\\n','g'), '/', '\\/', 'g')<CR>//gc
nmap <leader>zc :call Zdiff()<cr>
nmap <leader>zp :call ZdiffPrompt()<cr>
nmap <leader>zz :call Zinit()<cr>
nmap <leader>zi :call Zimport()<cr>
nmap <leader>si (V):EasyAlign /\<import\>/<cr>gvk:sort i<cr>
nmap <leader>zg :grep -tpy -tjs -w<Space>
nmap <leader>u :UndotreeToggle<cr>

" normal hard mode
" nmap <up> <nop>
" nmap <down> <nop>
" nmap <left> <nop>
" nmap <right> <nop>

" disable things that accidentally get hit...
imap <NUL> <Space>
nmap <F1> <nop>
imap <F1> <nop>
vmap <S-Up> <nop>
vmap <S-Down> <nop>
nmap <S-Up> <nop>
imap <S-Up> <nop>
imap <S-Down> <nop>
nmap <S-Down> <nop>
