set nocompatible
filetype off

let $VIMHOME=expand('~/dotfiles/')

" plugins
call plug#begin($VIMHOME.'/vim/plugged')
Plug 'bronson/vim-trailing-whitespace'
Plug 'dense-analysis/ale'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/vim-easy-align'
Plug 'lifepillar/vim-solarized8'
Plug 'ludovicchabant/vim-lawrencium'
Plug 'majutsushi/tagbar'
Plug 'mbbill/undotree'
Plug 'rakr/vim-one'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'will133/vim-dirdiff'
" Plug 'vim-scripts/DirDiff.vim'
Plug 'vimjas/vim-python-pep8-indent'
Plug 'endel/vim-github-colorscheme'
Plug 'NLKNguyen/papercolor-theme'
call plug#end()

set bg=light

" airline
let g:airline#extensions#tagbar#flags = 'f'

" ale
let g:ale_linters = { 'python': ['pyflakes'], 'javascript': ['jshint'] }
lef g:ale_jshint_config_loc = '$VIMHOME/dotfiles/jshint.config'
let g:python_pyflakes_executable = 'c:/ZogoTech/src/server/bin/zpyflakes'
let g:ale_enabled = 0
nmap <leader>ll :lopen<cr>
nmap <leader>lc :lclose<cr>

" lawrencium
nmap <leader>hg :tabnew %<cr>:Hgvdiff<cr><c-w><c-r>

" set spelling for hg commit messages
autocmd FileType hgcommit setlocal spell
autocmd FileType gitcommit setlocal spell

" vim settings
syntax on "syntax highlighting
set nowmnu
set wildmode=longest:full,full
filetype plugin on "make commands smarter for your file ]m and the like
filetype indent on
set clipboard=unnamed " set clipboard to system clipboard (gui compile req)
set backspace=2 " make backspace behave correctly!
set incsearch "jump to first match when searching
set tags=./tags,tags "look for a tags file all the way up till the root
set expandtab shiftwidth=4 softtabstop=4 " use spaces for tabs and 4 wide
set tabstop=4 " tabstop every 4 spaces
autocmd BufWritePre * :%s/\s\+$//e "delete trailing whitespace on save
set autoread " automatically read files when changed by another editor
" set hidden " just hide the buffer till I come back to it
set ignorecase " ignore case while searching
set wildignore+=*/.git/*,*/.hg/*,*.pyc,*.DS_Store "don't pick up certain things
set noswapfile
" set nobackup
set complete=.,w,b,u ",t,i
set completeopt=
set iskeyword+=\-
set shellslash " use forward slashes in paths like /ZogoTech/src
" set formatoptions +=j
set encoding=utf-8
set splitbelow
" set foldmethod=indent
" set foldlevelstart=20
set cc=80 " put a line at column 80
nmap <leader>h :set hlsearch! hlsearch?<CR>
nmap <leader>i :edit $VIMHOME/vim/vimrc<cr>
nmap <leader>ii :so %<cr>
nmap <leader>n :set number!<cr>
nmap <leader>r yiw:,$s/"//gc<left><left><left>
vmap <leader>r y:,$s/"//gc<left><left><left>
nmap <leader>v <c-w>v:vertical resize 85<cr><c-w>w
" set fillchars+=vert:┊
set fillchars+=vert:\  " remove the vert fill char
" no folding ever
au BufRead * set nofen
au BufRead * set nofen
" persist the undos
set undodir=~/.vim/undodir
set undofile
" just paste it!
nmap <leader>p "0p
" you have many colors... use them!
set termguicolors

set formatoptions+=j " Delete comment character when joining commented lines

" grep
autocmd QuickFixCmdPost *grep* cwindow
if executable("rg")
    set grepprg=rg\ --vimgrep\ --follow
endif
nmap <leader>g :grep -w<Space>

" statusline
set laststatus=2                                "always show status line
set statusline=\                                " start it off
set statusline+=%f\                             "File+path
if match(&runtimepath, 'Tagbar') != -1
    set statusline+=[
    " set statusline+=%#TagBarColor#
    set statusline+=%{tagbar#currenttag('%s','','f')}
    " set statusline+=%#StatusLine#
    set statusline+=]
else
    echo "Tagbar Not Installed"
endif
set statusline+=%*%=
set statusline+=%m\ "
set statusline+=%R%W%Y
set statusline+=,%{&ff}                       "FileFormat (dos/unix..)
set statusline +=%5l                          "current line
set statusline +=/%L                         "total lines
set statusline +=\                              "just a space

" python stuff
let g:python_pep8_indent_multiline_string = -2
let g:python_pep8_indent_hang_closing = 1
au BufNewFile,BufRead *.py set cc=73,80
au BufNewFile,BufRead *.py call ale#toggle#Enable()
ab pdb breakpoint() # TODO: remove this!!!
vmap <leader>wc <esc>:set textwidth=79<cr>gvgq<esc>:set textwidth=0<cr>gv
vmap <leader>wt <esc>:set textwidth=72<cr>gvgq<esc>:set textwidth=0<cr>gv

" NO MOUSE ALLOWED!
" set mouse=
:nmap <ScrollWheelUp> <nop>
:nmap <S-ScrollWheelUp> <nop>
:nmap <C-ScrollWheelUp> <nop>
:nmap <ScrollWheelDown> <nop>
:nmap <S-ScrollWheelDown> <nop>
:nmap <C-ScrollWheelDown> <nop>
:nmap <ScrollWheelLeft> <nop>
:nmap <S-ScrollWheelLeft> <nop>
:nmap <C-ScrollWheelLeft> <nop>
:nmap <ScrollWheelRight> <nop>
:nmap <S-ScrollWheelRight> <nop>
:nmap <C-ScrollWheelRight> <nop>

" FZF
let $FZF_DEFAULT_COMMAND = 'rg --files --follow --path-separator /'
let $FZF_DEFAULT_OPTS = '--color=bw'
let $PYTHONUNBUFFERED = 1
nmap <leader>e :FZF<cr>
nmap <leader>b :BTags<cr>
nmap <leader>t :Tags<cr>

" DirDiff
let g:DirDiffExcludes = ".hg,tags,*.pyc,.*.swp,.DS_Store,meta,__pycache__"
nmap <leader>dj :DirDiffNext<cr>
nmap <leader>dk :DirDiffPrev<cr>
nmap <leader>dc 2<c-w>w]czz
set diffopt+=context:9999
hi DiffAdd ctermfg=15 guifg=NONE ctermbg=10 guibg=darkseagreen1
hi DiffChange ctermfg=15 guifg=black ctermbg=11 guibg=lightcyan1
hi DiffText ctermfg=15 guifg=black ctermbg=1 guibg=cadetblue1
hi DiffDelete ctermfg=15 guifg=mistyrose ctermbg=12 guibg=mistyrose

" ZogoTech Stuff
function! Zinit()
    " change the root directory
    cd c:/ZogoTech/src
    " tag project files
    term ++close ctags -R --exclude=.hg --exclude=*.min.js --exclude=3p --languages=Python,Javascript --python-kinds=cfmvl appserver server webserver
    let $FZF_DEFAULT_COMMAND = 'rg --files --follow --type=py --type=js --type=txt --type=css --path-separator / appserver server webserver'
endfunc

function! Zimport()
    term ++close clipimport.bat
endfunc

function! Zdiff()
    let level = input('Version: ', '8.0')
    execute 'only'
    execute 'DirDiff c:/ZogoTech/hg/' . level . ' c:/ZogoTech/src'
endfunc

nmap <leader>07 :%s/<c-r>=substitute(substitute(substitute(substitute(substitute(substitute(substitute(@0, 'ALVIN', '.*', 'g'), '\\', '\\\\', 'g'), '\]', '\\]', 'g'), '\[', '\\[', 'g'), '[0-9]\+', '\[0-9\]\\+', 'g'), '\n','\\n','g'), '/', '\\/', 'g')<CR>//gc
nmap <leader>zc :call Zdiff()<cr>
nmap <leader>zz :call Zinit()<cr>
nmap <leader>zi :call Zimport()<cr>
map <leader>si (/import<cr>V)k:EasyAlign<cr><c-x>import<cr>(/import<cr>V)k:sort i<cr>
nmap <leader>zg :grep -tpy -tjs -w<Space>

" disable things that accidentally get hit...
imap <NUL> <Space>
nmap <F1> <nop>
imap <F1> <nop>
vmap <S-Up> <nop>
vmap <S-Down> <nop>
nmap <S-Up> <nop>
imap <S-Up> <nop>
imap <S-Down> <nop>
nmap <S-Down> <nop>
