set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'altercation/vim-colors-solarized'
Plugin 'bronson/vim-trailing-whitespace'
Plugin 'kien/ctrlp.vim'
Plugin 'ludovicchabant/vim-lawrencium'
Plugin 'pangloss/vim-javascript'
Plugin 'rking/ag.vim'
Plugin 'scrooloose/syntastic'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-unimpaired'
Plugin 'vim-scripts/DirDiff.vim'
Plugin 'vim-scripts/occur.vim'
call vundle#end()
filetype plugin on
syntax on

" abbreviations
ab pdb import pdb; pdb.set_trace()

" dirdiff setup
let g:DirDiffExcludes = ".hg,tags,*.pyc,.*.swp,.DS_Store,.meta"
set diffopt+=context:99999
let g:DirDiffEnableMappings = 1

" solarized
let g:solarized_bold=0      " no bold
let g:solarized_underline=0 " no underline
let g:solarized_italic=0    " no italic
colorscheme solarized       " use solarized colors

" syntastic
let g:syntastic_mode_map = { 'mode': 'passive' }
let g:syntastic_python_checkers = ['pyflakes']
let g:syntastic_javascript_checkers = ['jshint']

" setup terminal mode in nvim
:tnoremap <Esc> <C-\><C-n>
:tnoremap <A-h> <C-\><C-n><C-w>h
:tnoremap <A-j> <C-\><C-n><C-w>j
:tnoremap <A-k> <C-\><C-n><C-w>k
:tnoremap <A-l> <C-\><C-n><C-w>l

" configure vim settings
set expandtab           " use spaces not tabs
set tabstop=4           " tab is 4 spaces wide
set shiftwidth=4        " shift moves 4 spaces
set softtabstop=4       " soft tab is 4 spaces
set autoindent          " indednt to previous lines level
set tags=tags;/         " search for tags file in parent folders
set nowmnu              " turn off the menu on completion
set wildmode=full       " just show the first match on tab complete
set number              " show line numbers
set autoread            " warn when files are changed by another editor
set cc=80               " draw a line at 80 chars
set laststatus=2        " always show the status line
set complete=.,w,b,u,t  " setup the file scanning for find
set completeopt=        " turn off the completion menu
set incsearch           " jump to the first match when searching
set hidden              " hide buffers when I close them (not quit)
set path=$PWD/**        " set the current dir to the opened file (for find)
set noswapfile          " turn off swapfile
set nobackup            " turn off backup files
set wildignore+=*/.git/*,*/.hg/*,*.pyc,*.DS_Store "don't pick up certain things

" python specific settings
autocmd FileType python setlocal cc=72,79      " set the pep8 rules
autocmd FileType python setlocal iskeyword+=\- " treat dash as word

" highlight whitespace
match ErrorMsg '\(\s\+$\|\t\)'

" remove trailing whitespace
function! TrimWhiteSpace()
        %s/\s\+$//e
        endfunction

autocmd FileWritePre * :call TrimWhiteSpace()
autocmd FileAppendPre * :call TrimWhiteSpace()
autocmd FilterWritePre * :call TrimWhiteSpace()
autocmd BufWritePre * :call TrimWhiteSpace()

" custom status line
set statusline=\                                        " start it off
set statusline+=%f\                                     " File+path
set statusline+=%y\                                     " FileType
set statusline+=[%{&ff}]\                               " FileFormat (dos/unix..)
set statusline+=%m%r%w\                                 " Modified? Readonly? Top/bot.
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
set statusline +=%=%5l                                  " current line
set statusline +=/%L\ \                                 " total lines

" hard mode
" noremap <Up> <Nop>
" noremap <Down> <Nop>
" noremap <Left> <Nop>
" noremap <Right> <Nop>

" map leader keys
nmap <leader>00 :%s/<c-r>=substitute(substitute(@0,'\n','\\n','g'), '/', '\\/', 'g')<CR>//gc
nmap <leader>09 :%s/<c-r>=substitute(substitute(substitute(@0, '[0-9]\+', '\[0-9\]\\+', 'g'), '\n','\\n','g'), '/', '\\/', 'g')<CR>//gc
nmap <leader>xe :%!openssl base64<cr>
nmap <leader>xd :%!openssl base64 -d<cr>
nmap <leader>j :set textwidth=70<cr>:r !date<cr><s-o><esc><s-o><cr>
nmap <leader>e :find<space>
nmap <leader>b :CtrlPBufTag<cr>
nmap <leader>v <c-w>v:vertical resize 90<cr><c-w>w:find<space>
nmap <leader>n :call NumberToggle()<cr>
nmap <leader>t :echo system("date +'%r'")<cr>
nmap <leader>dc 2<c-w>w]c
imap <NUL> <Space>
map <leader>] :split <CR>:exec("tag ".expand("<cword>"))<CR>
nmap <leader>p :w !python<cr>
